# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi_service.proto\x12\x0c\x61pi.api_grpc\"2\n\x0eMessageRequest\x12\x12\n\nsenderName\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"!\n\x0fMessageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2X\n\nApiService\x12J\n\x0bSendMessage\x12\x1c.api.api_grpc.MessageRequest\x1a\x1d.api.api_grpc.MessageResponseb\x06proto3')



_MESSAGEREQUEST = DESCRIPTOR.message_types_by_name['MessageRequest']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUEST,
  '__module__' : 'api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.api_grpc.MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.api_grpc.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

_APISERVICE = DESCRIPTOR.services_by_name['ApiService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEREQUEST._serialized_start=35
  _MESSAGEREQUEST._serialized_end=85
  _MESSAGERESPONSE._serialized_start=87
  _MESSAGERESPONSE._serialized_end=120
  _APISERVICE._serialized_start=122
  _APISERVICE._serialized_end=210
# @@protoc_insertion_point(module_scope)
