# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12math_service.proto\x12\x04grpc\"\x1c\n\nIntRequest\x12\x0e\n\x06numInt\x18\x01 \x01(\x05\"\x1d\n\x0bIntResponse\x12\x0e\n\x06numInt\x18\x01 \x01(\x05\"!\n\rFloatResponse\x12\x10\n\x08numFloat\x18\x01 \x01(\x02\" \n\x0c\x46loatRequest\x12\x10\n\x08numFloat\x18\x01 \x01(\x02\x32\xcd\x01\n\x0bMathService\x12-\n\x04Sqrt\x12\x10.grpc.IntRequest\x1a\x13.grpc.FloatResponse\x12.\n\x03Std\x12\x10.grpc.IntRequest\x1a\x13.grpc.FloatResponse(\x01\x12/\n\x06\x46\x61\x63tor\x12\x10.grpc.IntRequest\x1a\x11.grpc.IntResponse0\x01\x12.\n\x03Max\x12\x10.grpc.IntRequest\x1a\x11.grpc.IntResponse(\x01\x30\x01\x62\x06proto3')



_INTREQUEST = DESCRIPTOR.message_types_by_name['IntRequest']
_INTRESPONSE = DESCRIPTOR.message_types_by_name['IntResponse']
_FLOATRESPONSE = DESCRIPTOR.message_types_by_name['FloatResponse']
_FLOATREQUEST = DESCRIPTOR.message_types_by_name['FloatRequest']
IntRequest = _reflection.GeneratedProtocolMessageType('IntRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTREQUEST,
  '__module__' : 'math_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.IntRequest)
  })
_sym_db.RegisterMessage(IntRequest)

IntResponse = _reflection.GeneratedProtocolMessageType('IntResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTRESPONSE,
  '__module__' : 'math_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.IntResponse)
  })
_sym_db.RegisterMessage(IntResponse)

FloatResponse = _reflection.GeneratedProtocolMessageType('FloatResponse', (_message.Message,), {
  'DESCRIPTOR' : _FLOATRESPONSE,
  '__module__' : 'math_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.FloatResponse)
  })
_sym_db.RegisterMessage(FloatResponse)

FloatRequest = _reflection.GeneratedProtocolMessageType('FloatRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLOATREQUEST,
  '__module__' : 'math_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.FloatRequest)
  })
_sym_db.RegisterMessage(FloatRequest)

_MATHSERVICE = DESCRIPTOR.services_by_name['MathService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTREQUEST._serialized_start=28
  _INTREQUEST._serialized_end=56
  _INTRESPONSE._serialized_start=58
  _INTRESPONSE._serialized_end=87
  _FLOATRESPONSE._serialized_start=89
  _FLOATRESPONSE._serialized_end=122
  _FLOATREQUEST._serialized_start=124
  _FLOATREQUEST._serialized_end=156
  _MATHSERVICE._serialized_start=159
  _MATHSERVICE._serialized_end=364
# @@protoc_insertion_point(module_scope)
